repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

#  - repo: https://github.com/psf/black
#    rev: 25.1.0
#    hooks:
#      - id: black